export const SELECT_OPTIONS = {
    gender: [
        { value: 'female', label: 'Female' },
        { value: 'male', label: 'Male' },
    ],
    barangay: [
        { value: 'A. O. Floirendo', label: 'A. O. Floirendo' },
        { value: 'Datu Abdul Dadia', label: 'Datu Abdul Dadia' },
        { value: 'Buenavista', label: 'Buenavista' },
        { value: 'Cacao', label: 'Cacao' },
        { value: 'Cagangohan', label: 'Cagangohan' },
        { value: 'Consolacion', label: 'Consolacion' },
        { value: 'Dapco', label: 'Dapco' },
        { value: 'Gredu', label: 'Gredu' },
        { value: 'J.P. Laurel', label: 'J.P. Laurel' },
        { value: 'Kasilak', label: 'Kasilak' },
        { value: 'Katipunan', label: 'Katipunan' },
        { value: 'Katualan', label: 'Katualan' },
        { value: 'Kauswagan', label: 'Kauswagan' },
        { value: 'Kiotoy', label: 'Kiotoy' },
        { value: 'Little Panay', label: 'Little Panay' },
        { value: 'Lower Panaga (Roxas)', label: 'Lower Panaga (Roxas)' },
        { value: 'Mabunao', label: 'Mabunao' },
        { value: 'Maduao', label: 'Maduao' },
        { value: 'Malativas', label: 'Malativas' },
        { value: 'Manay', label: 'Manay' },
        { value: 'Nanyo', label: 'Nanyo' },
        { value: 'New Malaga (Dalisay)', label: 'New Malaga (Dalisay)' },
        { value: 'New Malitbog', label: 'New Malitbog' },
        { value: 'New Pandan', label: 'New Pandan' },
        { value: 'New Visayas', label: 'New Visayas' },
        { value: 'Quezon', label: 'Quezon' },
        { value: 'Salvacion', label: 'Salvacion' },
        { value: 'San Francisco', label: 'San Francisco' },
        { value: 'San Nicolas', label: 'San Nicolas' },
        { value: 'San Pedro', label: 'San Pedro' },
        { value: 'San Roque', label: 'San Roque' },
        { value: 'San Vicente', label: 'San Vicente' },
        { value: 'Santa Cruz', label: 'Santa Cruz' },
        { value: 'Santo Niño', label: 'Santo Niño' },
        { value: 'Sindaton', label: 'Sindaton' },
        { value: 'Southern Davao', label: 'Southern Davao' },
        { value: 'Tagpore', label: 'Tagpore' },
        { value: 'Tibungol', label: 'Tibungol' },
        { value: 'Upper Licanan', label: 'Upper Licanan' },
        { value: 'Waterfall', label: 'Waterfall' },
    ],
}