import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { SessionProvider } from 'next-auth/react'
import { QueryClient } from '@tanstack/react-query'
import ReactQueryProvider from '@/components/providers/ReactQueryProvider'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons: {
        icon: '/img/cthall-logo-removedBG.png',
    },
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const queryClient = new QueryClient()

    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <SessionProvider refetchInterval={5 * 60} refetchOnWindowFocus={true}>
                    <ReactQueryProvider>{children}</ReactQueryProvider>
                </SessionProvider>
            </body>
        </html>
    )
}
